CHAPITRE11_VIDEO08_01/EvaluationProduit/EvaluationProduit.MVC/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EvaluationProduit.MVC.Filters;
using EvaluationProduit.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using EvaluationProduit.MVC.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace EvaluationProduit.MVC.Controllers
{
    public class ProduitController : Controller
    {
        private readonly IProduitService _produitService;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProduitController(IProduitService produitService, IWebHostEnvironment webHostEnvironment)
        {
            _produitService = produitService;
            this.webHostEnvironment = webHostEnvironment;
        }

        //[Route("Produit")]
        //[Route("Produit/Index")]
        //[Route("Produit/{id}")]
        //[ProduitActionFilter]
        [ServiceFilter(typeof(ProduitActionFilter))]
        public IActionResult Index()
        {
            string controller = (string)RouteData.Values["Controller"];

            string id = (string)RouteData.Values["id"];
            ViewBag.Message = "Liste des produits:";

            //return View(ListDesProduits());
            return View(_produitService.ProduitModels);
        }

        //public ContentResult Index()
        //{
        //    //return View(ListDesProduits());
        //    return Content("Bienvenue dans notre cours");
        //}

        //public ViewResult Index()
        //{
        //    return View(_produitService.ProduitModels);
        //}
        //public StatusCodeResult Index()
        //{
        //    return new StatusCodeResult(200);
        //}
        public IActionResult RedirectionVersIndex()
        {
            return RedirectToAction("Index");
        }
        [Route("Produit/Nouveau")]
        public IActionResult Ajouter(ProduitModel model)
        {
            if (ModelState.IsValid)
            {
                var photoModel = ChargerFichier(model.Photo.FichierPhoto);
                model.Photo = photoModel;
                model.Id = _produitService.ProduitModels.Select(p => p.Id).LastOrDefault()+1;
                _produitService.ProduitModels.Add(model);
                return RedirectToAction("Index", model);
            }

            var errors = ModelState.Select(x => x.Value.Errors)
                .Where(y => y.Count > 0)
                .ToList();

            return View();
        }

        public IActionResult Modifier(int id)
        {
            var produitModel = _produitService.ProduitModels.FirstOrDefault(p => p.Id.Equals(id));
            return View(produitModel);
        }

        public IActionResult Details(int id)
        {
            var idProduit = id;
            return View();
        }

        public IActionResult Supprimer(int id)
        {
            var produitModel = _produitService.ProduitModels.FirstOrDefault(p => p.Id.Equals(id));
            return View(produitModel);
        }

        public IActionResult SupprimerProduit(int id)
        {
            var produitModel = _produitService.ProduitModels.FirstOrDefault(p => p.Id.Equals(id));
            _produitService.ProduitModels.Remove(produitModel);
            return RedirectToAction("Index", _produitService.ProduitModels);
        }

        //private IList<ProduitModel> ListDesProduits()
        //{
        //    var produitModels = new List<ProduitModel>();
        //    var rnd = new Random();
        //    for (int i = 0; i < 40; i++)
        //    {
        //        var produitModel = new ProduitModel
        //        {
        //            Id = i,
        //            DateCreation = DateTime.Now,
        //            Description = $"C'est la description du produit numéro:{i}",
        //            MoyenneEvaluation = 0,
        //            Nom = $"Produit-:{i}",
        //            Prix = rnd.Next(),
        //            CategorieModel = new CategorieModel
        //            {
        //                Id = i,
        //                Nom = $"Catégorie:{i}"
        //            }
        //        };
        //        produitModels.Add(produitModel);
        //    }
        //    return produitModels;
        //}

        private PhotoModel ChargerFichier(IFormFile photoFile)
        {
            var photoModel = new PhotoModel();
            if (photoFile != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                photoModel.Titre = Guid.NewGuid().ToString() + "_" + photoFile.FileName;
                photoModel.DateCreation = DateTime.Now;
                photoModel.PhotoID = Guid.NewGuid().ToString();
                string filePath = Path.Combine(uploadsFolder, photoModel.Titre);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    photoFile.CopyTo(fileStream);
                }
            }
            return photoModel;
        }
    }
}

CHAPITRE11_VIDEO08_01/EvaluationProduit/EvaluationProduit.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Évaluation d'un produit</title>
    <environment include="Developement">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Developement">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EvaluationProduit.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-md">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width: 64px;" src="~/images/rating.png" class="img-fluid" alt="Évaluer un produit">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">

                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produit" asp-action="Index">Liste des produits</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EvaluationProduit.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CHAPITRE11_VIDEO08_01/EvaluationProduit/EvaluationProduit.MVC/Views/Shared/_ListPartialView.cshtml
@model EvaluationProduit.MVC.Models.ModeleBase;
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <td>
        @Html.DisplayFor(modelItem => Model.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Nom)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.DateCreation)
    </td>